import type { AppState } from '@/types';
import { today, addDays } from './date';

export function createInitialState(): AppState {
  return {
    character: {
      name: 'Wren',
      level: 1,
      xp: 0,
      xpToNext: 100,
      mood: 'calm',
      coins: 50,
      hairColor: '#8b5a3c',
      skinTone: '#f4d3b3',
      outfitColor: '#8bb46a',
      hat: '🌿',
    },
    tasks: [
      {
        id: 't1',
        title: 'Water the plants',
        notes: 'A gentle morning ritual.',
        questType: 'daily',
        targetDate: today(),
        graceDays: 1,
        completed: false,
        createdAt: new Date().toISOString(),
      },
      {
        id: 't2',
        title: 'Read 10 cozy pages',
        questType: 'daily',
        targetDate: today(),
        graceDays: 2,
        completed: false,
        createdAt: new Date().toISOString(),
      },
      {
        id: 't3',
        title: 'Tidy up the desk corner',
        questType: 'weekly',
        targetDate: addDays(today(), 3),
        graceDays: 3,
        completed: false,
        createdAt: new Date().toISOString(),
      },
    ],
    projects: [
      {
        id: 'p1',
        title: 'Plant a Tiny Garden',
        description: 'Grow a small herb garden on the windowsill.',
        emoji: '🌱',
        color: '#8bb46a',
        milestones: [
          { id: 'm1', title: 'Pick three herbs', done: true },
          { id: 'm2', title: 'Buy pots and soil', done: false },
          { id: 'm3', title: 'Plant seeds', done: false },
          { id: 'm4', title: 'First sprout!', done: false },
        ],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'p2',
        title: 'Learn Watercolor',
        description: 'A soft creative quest, one brushstroke at a time.',
        emoji: '🎨',
        color: '#c9b3e0',
        milestones: [
          { id: 'm5', title: 'Gather supplies', done: false },
          { id: 'm6', title: 'First color study', done: false },
          { id: 'm7', title: 'Paint a tiny landscape', done: false },
        ],
        createdAt: new Date().toISOString(),
      },
    ],
    habits: [
      {
        id: 'h1',
        title: 'Drink water',
        emoji: '💧',
        frequency: 'daily',
        streak: 3,
        longestStreak: 5,
        history: [today()],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'h2',
        title: 'Gentle stretch',
        emoji: '🧘',
        frequency: 'daily',
        streak: 1,
        longestStreak: 7,
        history: [],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'h3',
        title: 'Walk outside',
        emoji: '🌲',
        frequency: 'weekly',
        streak: 2,
        longestStreak: 4,
        history: [],
        createdAt: new Date().toISOString(),
      },
    ],
    achievements: [
      { id: 'a1', title: 'First Bloom', description: 'Complete your first task.', emoji: '🌸', unlocked: false, category: 'productivity' },
      { id: 'a2', title: 'Cozy Centurion', description: 'Complete 100 tasks.', emoji: '🏆', unlocked: false, category: 'productivity' },
      { id: 'a3', title: 'Master Gardener', description: 'Complete 1000 tasks.', emoji: '🌳', unlocked: false, category: 'productivity' },
      { id: 'a4', title: 'Weekly Glow', description: 'Reach a 7-day streak.', emoji: '✨', unlocked: false, category: 'consistency' },
      { id: 'a5', title: 'Monthly Moonlight', description: 'Reach a 30-day streak.', emoji: '🌙', unlocked: false, category: 'consistency' },
      { id: 'a6', title: 'Hundred Days of Care', description: 'Reach a 100-day streak.', emoji: '💫', unlocked: false, category: 'consistency' },
      { id: 'a7', title: 'Cottage Explorer', description: 'Unlock a new world area.', emoji: '🗺️', unlocked: false, category: 'exploration' },
      { id: 'a8', title: 'Home Sweet Home', description: 'Decorate your room.', emoji: '🛋️', unlocked: false, category: 'exploration' },
    ],
    areas: [
      { id: 'cottage', name: 'Starter Cottage', emoji: '🏡', description: 'Your warm little home.', requiredLevel: 1, unlocked: true },
      { id: 'garden', name: 'Garden', emoji: '🌷', description: 'A blooming patch outside the door.', requiredLevel: 2, unlocked: false },
      { id: 'forest', name: 'Whisper Forest', emoji: '🌲', description: 'Tall trees and friendly fireflies.', requiredLevel: 4, unlocked: false },
      { id: 'beach', name: 'Pebble Beach', emoji: '🏖️', description: 'Soft waves and warm sand.', requiredLevel: 6, unlocked: false },
      { id: 'mountain', name: 'Quiet Mountain', emoji: '⛰️', description: 'Peaceful peaks and slow snow.', requiredLevel: 8, unlocked: false },
      { id: 'town', name: 'Town Square', emoji: '🏘️', description: 'A friendly gathering place.', requiredLevel: 10, unlocked: false },
      { id: 'observatory', name: 'Observatory', emoji: '🔭', description: 'A roof full of stars.', requiredLevel: 14, unlocked: false },
      { id: 'festival', name: 'Festival Grounds', emoji: '🎪', description: 'Where seasons celebrate.', requiredLevel: 18, unlocked: false },
    ],
    shop: [
      { id: 's1', name: 'Cozy Beanie', emoji: '🧢', category: 'clothing', price: 40, owned: false },
      { id: 's2', name: 'Sun Hat', emoji: '👒', category: 'clothing', price: 60, owned: false },
      { id: 's3', name: 'Knit Scarf', emoji: '🧣', category: 'clothing', price: 50, owned: false },
      { id: 's4', name: 'Round Glasses', emoji: '👓', category: 'clothing', price: 35, owned: false },
      { id: 's5', name: 'Pet Cat', emoji: '🐱', category: 'accessory', price: 150, owned: false },
      { id: 's6', name: 'Tiny Backpack', emoji: '🎒', category: 'accessory', price: 80, owned: false },
      { id: 's7', name: 'Ukulele', emoji: '🪕', category: 'accessory', price: 120, owned: false },
      { id: 's8', name: 'Potted Fern', emoji: '🪴', category: 'decoration', price: 45, owned: false },
      { id: 's9', name: 'Reading Lamp', emoji: '💡', category: 'decoration', price: 70, owned: false },
      { id: 's10', name: 'Bookshelf', emoji: '📚', category: 'decoration', price: 110, owned: false },
      { id: 's11', name: 'Soft Rug', emoji: '🟫', category: 'decoration', price: 65, owned: false },
      { id: 's12', name: 'Window Frame', emoji: '🪟', category: 'decoration', price: 90, owned: false },
    ],
    totalTasksCompleted: 0,
    loginStreak: 1,
  };
}
